// <auto-generated />
using System;
using DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260402134514_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.14");

            modelBuilder.Entity("Common.Models.ImportBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExportVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ExportVersion");

                    b.Property<DateTimeOffset>("ExportedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("ExportedAt");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("ImportedAt");

                    b.Property<int>("RecordCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("RecordCount");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .HasColumnName("Source");

                    b.HasKey("Id");

                    b.ToTable("ImportBatch", (string)null);
                });

            modelBuilder.Entity("Common.Models.StepEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Count");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("Date");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("EndTime");

                    b.Property<int>("ImportBatchId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ImportBatchId");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("StartTime");

                    b.HasKey("Id");

                    b.HasIndex("ImportBatchId");

                    b.ToTable("StepEntry", (string)null);
                });

            modelBuilder.Entity("Common.Models.StepEntry", b =>
                {
                    b.HasOne("Common.Models.ImportBatch", "ImportBatch")
                        .WithMany("StepEntries")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportBatch");
                });

            modelBuilder.Entity("Common.Models.ImportBatch", b =>
                {
                    b.Navigation("StepEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
