// <auto-generated />
using System;
using DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260407121315_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.14");

            modelBuilder.Entity("Common.Models.ActivityDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("Date");

                    b.Property<double>("DistanceMeters")
                        .HasColumnType("REAL")
                        .HasColumnName("DistanceMeters");

                    b.Property<DateTime>("EndTimeUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("EndTimeUtc");

                    b.Property<int>("LastImportBatchId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LastImportBatchId");

                    b.Property<DateTime>("LastImportedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("LastImportedAtUtc");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .HasColumnName("Source");

                    b.Property<DateTime>("StartTimeUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("StartTimeUtc");

                    b.Property<int>("Steps")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Steps");

                    b.HasKey("Id");

                    b.HasIndex("LastImportBatchId");

                    b.HasIndex("Source", "Date")
                        .IsUnique();

                    b.ToTable("ActivityDay", (string)null);
                });

            modelBuilder.Entity("Common.Models.ImportBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExportVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ExportVersion");

                    b.Property<DateTime>("ExportedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("ExportedAtUtc");

                    b.Property<DateTime>("ImportedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("ImportedAtUtc");

                    b.Property<int>("InsertedRecordCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("InsertedRecordCount");

                    b.Property<DateTime>("RangeEndUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("RangeEndUtc");

                    b.Property<DateTime>("RangeStartUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("RangeStartUtc");

                    b.Property<int>("ReceivedRecordCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ReceivedRecordCount");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .HasColumnName("Source");

                    b.Property<int>("UnchangedRecordCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UnchangedRecordCount");

                    b.Property<int>("UpdatedRecordCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UpdatedRecordCount");

                    b.HasKey("Id");

                    b.ToTable("ImportBatch", (string)null);
                });

            modelBuilder.Entity("Common.Models.ActivityDay", b =>
                {
                    b.HasOne("Common.Models.ImportBatch", "LastImportBatch")
                        .WithMany("ActivityDayEntries")
                        .HasForeignKey("LastImportBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LastImportBatch");
                });

            modelBuilder.Entity("Common.Models.ImportBatch", b =>
                {
                    b.Navigation("ActivityDayEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
